name: build-humble 

on:
  pull_request:
    types: [review_requested, ready_for_review]
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
      fail-fast: false
    steps:
      - name: Setup ros
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble
      - name: Checkout Aerostack2
        run : |
          echo 'repositories:\n  aerostack2:\n    type: git\n    url: https://github.com/aerostack2/aerostack2.git\n    version: main' >> /tmp/dependencies.repos
      - name: build and test
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: >
            as2_platform_dji_psdk
          target-ros2-distro: humble
          vcs-repo-file-url: /tmp/dependencies.repos
